name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  id-token: write
  pull-requests: write
jobs:
  terraform_prod:
    name: TF OIDC AUTH
    uses: fabrinator/actions/.github/workflows/terraform.yaml@feature/oidc-auth
    with:
      TERRAFORM_VERSION: "1.9.2"
      AWS_REGION: "us-east-1"
      TF_WORKING_DIRECTORY: "."
      TF_EXTRA_OPTIONS: "--var-file=fabririvas.com.tfvars"
    secrets: inherit
  terraform_dev:
    name: TF OIDC AUTH
    uses: fabrinator/actions/.github/workflows/terraform.yaml@feature/oidc-auth
    with:
      TERRAFORM_VERSION: "1.9.2"
      AWS_REGION: "us-east-1"
      TF_WORKING_DIRECTORY: "."
      TF_EXTRA_OPTIONS: "--var-file=stage.fabririvas.com.tfvars"
      TF_WORKSPACE: "dev"
    secrets: inherit