name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  id-token: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    environment:  auto
    steps:
      - run: echo hi
#    name: TF Live
#    uses: fabrinator/actions/.github/workflows/terraform.yaml@feature/oidc-auth
#    with:
#      TERRAFORM_VERSION: "1.9.2"
#      AWS_REGION: "us-east-1"
#      TF_WORKING_DIRECTORY: "."
#      TF_EXTRA_OPTIONS: "--var-file=fabririvas.com.tfvars"
#      TF_PROVIDER_AWS_ACCOUNT: 730335655220
#    secrets: inherit
