name: Terraform
run-name: Terraform workflow
on:
  label:
    types:
      - dev
permissions:
  id-token: write
  pull-requests: write
jobs:
  terraform:
    name: TF Dev
    uses: fabrinator/actions/.github/workflows/terraform.yaml@feature/oidc-auth
    with:
      TERRAFORM_VERSION: "1.9.2"
      AWS_REGION: "us-east-1"
      TF_WORKING_DIRECTORY: "."
      TF_EXTRA_OPTIONS: "--var-file=dev.fabririvas.com.tfvars"
      TF_WORKSPACE: "dev"
      TF_PROVIDER_AWS_ACCOUNT: 912008965710
    secrets: inherit