name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
jobs:
  configure_auth:
    runs-on: ubuntu-latest
    name: Requirements
    environment:  auto
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::621897290135:role/oidc-github-actions
          role-session-name: bootcamp-account
      - run: aws sts get-caller-identity
      - run: aws s3 ls
      - run: terraform init && terraform apply -auto-approve