name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  id-token: write
  pull-requests: write
jobs:
  terraform:
    name: TF OIDC AUTH
    uses: fabrinator/actions/.github/workflows/terraform.yaml@feature/oidc-auth
    with:
      TERRAFORM_VERSION: "1.9.2"
      AWS_REGION: "us-east-1"
      TF_WORKING_DIRECTORY: "."
    secrets: inherit