name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
jobs:
  configure_auth:
    runs-on: ubuntu-latest
    name: Requirements
    environment:  auto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir $HOME/.aws
      - run: mv aws.config $HOME/.aws/config
      - run : aws sso login  --no-browser
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.2"
      - run: terraform init && terraform apply -auto-approve
      - run: aws sts get-caller-identity --profile crc-dev