name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
jobs:
  configure_auth:
    runs-on: ubuntu-latest
    name: Requirements
    environment:  auto
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: https://device.sso.us-east-1.amazonaws.com/?user_code=SCMG-ZFKT


      - run: aws sts get-caller-identity
      - run: aws s3 ls