name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
jobs:
  configure_auth:
    runs-on: ubuntu-latest
    name: Requirements
    environment:  auto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::621897290135:role/oidc-github-actions
          role-session-name: bootcamp-account
      - run: aws sts get-caller-identity
      - run: aws s3 ls
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v7
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken('sts.amazonaws.com')
            coredemo.setOutput('id_token', id_token)
      - run: echo $VAR
        env:
          VAR: ${{ steps.idtoken.outputs.id_token }}
      - run: terraform init && terraform apply -auto-approve
        env:
          TF_VAR_ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.idtoken.outputs.id_token }}