name: Terraform
run-name: Terraform workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
jobs:
  configure_auth:
    runs-on: ubuntu-latest
    name: Requirements
    environment:  auto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::621897290135:role/oidc-github-actions
          role-session-name: bootcamp-account
      - run: aws sts get-caller-identity
      - run: aws s3 ls
      - uses: actions/github-script@v6
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())
      - run: echo $VAR
        env:
          VAR: ${{ steps.script.outputs.TOKEN }}
      - run: terraform init && terraform apply -auto-approve
        env:
          TF_VAR_ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.script.outputs.TOKEN }}